### ISSUE TITLE
Help with Plugin

### ISSUE THREAD

**Issue by OsandaMalith** [stonedreamforest/Mirage#11]
I've followed the steps and once I run the plugin I get this where the buttons don't work. Am I missing something?

![image](https://user-images.githubusercontent.com/4497190/77257520-e146c200-6c6c-11ea-80b8-f3425f879e7d.png)

**Comment by stonedreamforest** [comment]
your operating system version is not supported. 
- [Supported version](https://github.com/stonedreamforest/Mirage#%E7%B3%BB%E7%BB%9F%E6%94%AF%E6%8C%81)
  1. win7 x64 ( 6.1.7600)
  2. win10 19h1 x64 (10.0.18362.XXXX)
