### ISSUE TITLE
Version 10.0.19041.572

### ISSUE THREAD

**Issue by Barred0ut** [stonedreamforest/Mirage#16]
How much money do you want to make this supported? I don't wanna make 10 accounts and combo this thread till it's supported.

**Comment by stonedreamforest** [comment]
If  you are a novice and can't make money by this, I suggest you learn to bypass the protection yourself.

**Comment by Barred0ut** [comment]
Uggh... I can make money just fine, and all I was asking was if you wanted to get paid to make this plug in work with my version of windows. But whatever, kinda sucks majority of the plug-ins are half @ssed pieces of work that hardly work anyway. I've tried to make this garbage work to no avail. Nothing more I can do without the source.

**Comment by stonedreamforest** [comment]
@Barred0ut 
my paid price is $1,000(doesn't include deposit), which is just the starting price. If you confirm, please send an email to tell me and introduce more detailed content in it, for example, tell me your goal, I need to test it, of course, if you need to keep it confidential, then I will send you a private custom plug-in directly, and I will still Will use al-khaser test.
