### ISSUE TITLE
18362.418 R90VGCJP， 家庭中文版， 蓝屏

### ISSUE THREAD

**Issue by uvbs** [stonedreamforest/Mirage#2]
操作步骤都是按照10号更新的

**Comment by stonedreamforest** [comment]
请给我一个该版本的下载链接

**Comment by stonedreamforest** [comment]
使用此版本：
https://github.com/stonedreamforest/Mirage/releases/tag/v20191111
已在该本版下测试：
![image](https://user-images.githubusercontent.com/16742566/68570304-4d354480-049b-11ea-83be-fa5bab7eadce.png)

来自itellyou ：
![image](https://user-images.githubusercontent.com/16742566/68570342-6b9b4000-049b-11ea-8558-782c0fbc1fc5.png)
