### ISSUE TITLE
win10.18362 is 1903

### ISSUE THREAD

**Issue by killvxk** [stonedreamforest/Mirage#3]
19h1's buildnumber is between 17134 and 18362.

**Comment by stonedreamforest** [comment]
`17134` 应该是 `win10 RS4`  中间有个版本`17763` 应该是`RS5`

1903 也是19h1...
![image](https://user-images.githubusercontent.com/16742566/68574292-81f9c980-04a4-11ea-88b5-73281d7aec8a.png)
