### ISSUE TITLE
这是驱动加载不成功嘛

### ISSUE THREAD

**Issue by uvbs** [stonedreamforest/Mirage#5]
![image](https://user-images.githubusercontent.com/3278777/68660802-d2d8f300-0574-11ea-80c6-4ee4c313eb49.png)

**Comment by uvbs** [comment]
所有在 虚拟机下的系统都是这样，  win7 开启测试模式也加载不了驱动

**Comment by stonedreamforest** [comment]
对没加载成功 可以尝试：
![image](https://user-images.githubusercontent.com/16742566/68669007-7382df00-0584-11ea-948c-ce7a7b5447a4.png)

**Comment by uvbs** [comment]
![image](https://user-images.githubusercontent.com/3278777/68681546-87d3d580-059e-11ea-9359-efe7bc5cc68f.png)
WIN7 OK了， win10 还是有问题 驱动启动不成功

**Comment by uvbs** [comment]
有个问题  进入成功之后, 
![image](https://user-images.githubusercontent.com/3278777/68835900-14dc7300-06f4-11ea-8feb-5e0e7c7a9559.png)
如果x64dbg退出， 再打开x64dbg 就是失效的状态

**Comment by stonedreamforest** [comment]
win10加载不成功没遇到过 。
退出后再加载不成功会看下

**Comment by stonedreamforest** [comment]
使用这个版本：
https://github.com/stonedreamforest/Mirage/releases/tag/v20191116
