### ISSUE TITLE
Windows 10 English

### ISSUE THREAD

**Issue by UnlimitedChild** [stonedreamforest/Mirage#6]
Hi, 

the configuration file is not created on systems with a different language, such as English. Is it possible to add support for English translation?

Thanks!

P.S>Does the plugin work in a virtual machine?

**Comment by stonedreamforest** [comment]
The MVConfigBuild can create profiles in the English system and  the plugin support vm

**Comment by UnlimitedChild** [comment]
MVConfigBuild ntkrnlmp.pdb
[MVConfigBuild]г║╖√║┼╬─╝■╝╙╘╪╩з░▄

you did not check, nothing is created, tested on three machines.

**Comment by stonedreamforest** [comment]
You should make sure the MVConfigBuild.exe and msdia140.dll are in the same directory.

**Comment by stonedreamforest** [comment]
try this version: https://github.com/stonedreamforest/Mirage/releases/tag/v20191117
