### ISSUE TITLE
Unprocessed Hypervisor bit of CPUID instruction with EAX=1

### ISSUE THREAD

**Issue by nakido-official** [stonedreamforest/Mirage#8]
如题

**Comment by stonedreamforest** [comment]
这个错误是怎么出现的？你的cpu是intel的吗？支持vt吗？这个错误出现在实体机还是虚拟机？出现在哪个系统以及版本号？我如何复现它？![image](https://user-images.githubusercontent.com/16742566/75092408-2914f380-55b2-11ea-8dce-155aa4fac236.png)

**Comment by nakido-official** [comment]
不是错误。。
我是说你的VM没有处理CPUID指令1号功能ECX返回值的第31位，它用来指示Hypervisor是否存在，可以作为检测点，用了你的插件可能会被反VM误伤。

**Comment by stonedreamforest** [comment]
尝试使用这个版本：[v20200224](https://github.com/stonedreamforest/Mirage/releases/tag/v20200224)

有问题请随时打开issue
